# listener services that you can opt into for a repository
services:
    app.subscriber.status_change_by_comment_subscriber:
        class: AppBundle\Subscriber\StatusChangeByCommentSubscriber
        arguments:
            - '@app.status_api'
            - '@logger'

    app.subscriber.status_change_on_push_subscriber:
        class: AppBundle\Subscriber\StatusChangeOnPushSubscriber
        arguments:
            - '@app.status_api'

    app.subscriber.needs_review_new_pr_subscriber:
        class: AppBundle\Subscriber\NeedsReviewNewPRSubscriber
        arguments:
            - '@app.status_api'

    app.subscriber.bug_label_new_issue_subscriber:
        class: AppBundle\Subscriber\BugLabelNewIssueSubscriber
        arguments:
            - '@app.status_api'

    app.subscriber.auto_label_pr_from_content_subscriber:
        class: AppBundle\Subscriber\AutoLabelPRFromContentSubscriber
        arguments:
            - '@app.github.cached_labels_api'

    app.subscriber.new_pr_subscriber:
        class: AppBundle\Subscriber\NewPRSubscriber
        arguments:
            - '@app.status_api'

parameters:
    # point to the main symfony repositories
    repositories:
        profideo/sdk:
            subscribers:
                - app.subscriber.status_change_by_comment_subscriber
                - app.subscriber.needs_review_new_pr_subscriber
                - app.subscriber.bug_label_new_issue_subscriber
                - app.subscriber.auto_label_pr_from_content_subscriber
            # secret: change_me
        sowbiba/senegal-admin:
            subscribers:
                - app.subscriber.status_change_by_comment_subscriber
                - app.subscriber.needs_review_new_pr_subscriber
                - app.subscriber.bug_label_new_issue_subscriber
                - app.subscriber.auto_label_pr_from_content_subscriber
            # secret: change_me